[package]
name = "gruphst"
version = "0.1.0"
edition = "2021"
description = "An in-memory graph database"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.0"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.9.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
log = "0.4.21"
simple_logger = "5.0.0"
serial_test = "3.1.1"
